### PR TITLE
CI: Add copyright license check

### PR DESCRIPTION
**Pull request by tore-espressif**
Added copyright header check to pre-commit

### CODE REVIEW

**Review by roma-jam — APPROVED** [review]
LGTM.
Should we added the changes also to a git workflow?

**Review by peter-marcisovsky — APPROVED** [review]
I was checking whether you need to update the years on the license if you are changing the license itself, not the actual code. 

Found you it's ok the way as it is now. But, correct me if I am wrong.
Otherwise, LGTM.

**Comment by tore-espressif** [comment]
Thanks for the reviews!

@roma-jam  what do you mean by 

> Should we added the changes also to a git workflow?

If you have pre-commit installed the check will run automatically, so there is no need to do anything extra

**Comment by roma-jam** [comment]
@tore-espressif The same as you did here: https://github.com/espressif/esp-usb/pull/12?

**Comment by tore-espressif** [comment]
#12 added pre-commit run to CI. 

So this change will be automatically reflected in your local repo and also checked in CI

**Pull request merged**
